import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { existsSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { outlineToDeck, parseOutlineMarkdown, projectFromOutline } from "../src/from-outline.js";
import { renderPreviewHtml } from "../src/preview.js";
import {
  PAGE_PROTOTYPE_NAMES,
  fillPrototype,
  loadPagePrototype,
  outlineTextStyles,
  sectionPages,
  splitTextToFit,
} from "../src/internal/page-prototypes.js";
import { validateDeck } from "../src/validate.js";
import { qaDeck } from "../src/qa.js";
import { ErrorCodes, OpenPptError } from "../src/errors.js";
import { TEXT_INSET_Y_PX, ptToPx } from "../src/internal/units.js";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

function leafTexts(deck) {
  return (deck.pages || []).flatMap((page) =>
    (page.elements || []).filter((el) => el.type === "text"),
  );
}

function textPayload(el) {
  if (Array.isArray(el.paragraphs)) {
    return el.paragraphs
      .map((para) =>
        Array.isArray(para.text)
          ? para.text.map((run) => run.text ?? "").join("")
          : String(para.text ?? ""),
      )
      .join("\n");
  }
  if (Array.isArray(el.text)) {
    return el.text.map((run) => run.text ?? "").join("");
  }
  return String(el.text ?? "");
}

describe("C3 outline prototypes", () => {
  it("lays two peers in distinct columns at readable size without generator copy", () => {
    const deck = outlineToDeck(
      parseOutlineMarkdown("# D\n## Two\n- First peer\n- Second peer"),
    );
    const { deck: leaves } = validateDeck(deck, { checkMedia: false });
    const texts = leafTexts(leaves);
    assert.equal(
      texts.filter((el) => /generated by/i.test(textPayload(el))).length,
      0,
      "generated deck must not contain generator implementation copy",
    );

    const first = texts.find((el) => textPayload(el).includes("First peer"));
    const second = texts.find((el) => textPayload(el).includes("Second peer"));
    assert.ok(first, "first peer body text is present");
    assert.ok(second, "second peer body text is present");
    assert.notEqual(first.id, second.id, "peer bodies are distinct elements");
    const [x1, y1, w1] = first.bounds;
    const [x2, y2] = second.bounds;
    assert.notEqual(x1, x2, "two peer body boxes have distinct x positions");
    assert.equal(y1, y2, "two peer body boxes share the same y");
    assert.ok(x1 + w1 <= x2 || x2 + second.bounds[2] <= x1, "peer bodies sit in separate columns");
    assert.ok((first.fontSize ?? 0) >= 18, `first peer fontSize ${first.fontSize}`);
    assert.ok((second.fontSize ?? 0) >= 18, `second peer fontSize ${second.fontSize}`);
  });

  it("paginates one long CJK bullet across continued pages and keeps every segment", () => {
    const segments = Array.from(
      { length: 24 },
      (_, index) =>
        `第${index + 1}段：保留原始内容和数字，检查导出页面中的中文排版、换行及阅读顺序，确认分页后仍可读。`,
    );
    const bullet = segments.join("");
    assert.ok(bullet.length >= 600, `CJK bullet length ${bullet.length}`);
    const deck = outlineToDeck({
      title: "长内容",
      sections: [{ title: "单条中文长内容", bullets: [bullet] }],
    });
    const { deck: leaves } = validateDeck(deck, { checkMedia: false });
    const joined = leafTexts(leaves).map(textPayload).join("\n");
    for (const segment of segments) {
      assert.ok(joined.includes(segment), `retained ${segment.slice(0, 8)}`);
      assert.equal(
        joined.split(segment).length - 1,
        1,
        `segment ${segment.slice(0, 8)} must not be duplicated`,
      );
    }
    const bodyPages = leaves.pages.filter((page) =>
      (page.elements || []).some((el) => el.type === "text" && /第\d+段/.test(textPayload(el))),
    );
    assert.ok(bodyPages.length >= 2, "long CJK bullet continues across body pages");
    const continued = bodyPages.some((page) =>
      (page.elements || []).some(
        (el) =>
          el.type === "text" && /continued|续|接上/i.test(textPayload(el)),
      ),
    );
    assert.ok(continued, "continuation pages are clearly labeled");
    for (const el of leafTexts(leaves)) {
      if (!el.fontSize) continue;
      assert.ok(el.fontSize >= 18, `${el.id} fontSize ${el.fontSize} < 18`);
    }
    const qa = qaDeck(deck, { checkMedia: false, failOn: "med" });
    assert.equal(qa.ok, true, qa.issues.map((issue) => issue.code).join(","));
  });

  it("selects three-card geometry for three short peers", () => {
    const deck = outlineToDeck(
      parseOutlineMarkdown(
        "# D\n## Three\n- Alpha peer stays short\n- Bravo peer stays short\n- Charlie peer stays short",
      ),
    );
    const { deck: leaves } = validateDeck(deck, { checkMedia: false });
    const bodies = ["Alpha peer stays short", "Bravo peer stays short", "Charlie peer stays short"].map(
      (text) => {
        const el = leafTexts(leaves).find((node) => textPayload(node).includes(text));
        assert.ok(el, text);
        return el;
      },
    );
    const xs = new Set(bodies.map((el) => el.bounds[0]));
    const ys = new Set(bodies.map((el) => el.bounds[1]));
    assert.equal(xs.size, 3, "three card bodies have distinct x positions");
    assert.equal(ys.size, 1, "three card bodies share the same y");
    for (const el of bodies) assert.ok((el.fontSize ?? 0) >= 18);
  });

  it("selects KPI-row geometry only for explicit labels and values", () => {
    const deck = outlineToDeck(
      parseOutlineMarkdown(
        "# D\n## Reported measurements\n- Accepted checks: 42\n- Median latency: 180 ms\n- Coverage: 92%",
      ),
    );
    const { deck: leaves } = validateDeck(deck, { checkMedia: false });
    const texts = leafTexts(leaves);
    const value42 = texts.find((el) => textPayload(el).includes("42"));
    const value180 = texts.find((el) => textPayload(el).includes("180 ms"));
    const value92 = texts.find((el) => textPayload(el).includes("92%"));
    assert.ok(value42 && value180 && value92, "KPI values are present as distinct copy");
    assert.equal(new Set([value42.bounds[1], value180.bounds[1], value92.bounds[1]]).size, 1);
    assert.equal(new Set([value42.bounds[0], value180.bounds[0], value92.bounds[0]]).size, 3);
    const labelChecks = texts.find((el) => textPayload(el).includes("Accepted checks"));
    assert.ok(labelChecks);
    assert.notEqual(labelChecks.id, value42.id, "KPI label and value are separate boxes");
    const notKpi = outlineToDeck(
      parseOutlineMarkdown("# D\n## Wins\n- Closed three enterprise pilots\n- Kept two reviewers"),
    );
    const notKpiJoined = leafTexts(
      validateDeck(notKpi, { checkMedia: false }).deck,
    )
      .map(textPayload)
      .join("\n");
    assert.match(notKpiJoined, /Closed three enterprise pilots/);
    assert.equal(
      leafTexts(validateDeck(notKpi, { checkMedia: false }).deck).filter(
        (el) => (el.fontSize ?? 18) >= 28 && /^\s*3\s*$/.test(textPayload(el)),
      ).length,
      0,
      "unordered prose numbers are not fabricated KPI values",
    );
  });

  it("selects sequence layout only for explicit ordered input", () => {
    const deck = outlineToDeck(
      parseOutlineMarkdown(
        "# D\n## Explicit sequence\n1. Collect the supplied source material.\n2. Build and inspect the presentation.\n3. Record verified results and remaining uncertainty.",
      ),
    );
    const { deck: leaves } = validateDeck(deck, { checkMedia: false });
    const texts = leafTexts(leaves);
    const steps = [
      "Collect the supplied source material.",
      "Build and inspect the presentation.",
      "Record verified results and remaining uncertainty.",
    ].map((text) => {
      const el = texts.find((node) => textPayload(node).includes(text));
      assert.ok(el, text);
      return el;
    });
    const ys = steps.map((el) => el.bounds[1]);
    assert.ok(ys[0] < ys[1] && ys[1] < ys[2], "sequence steps are stacked in order");
    const markers = texts.filter((el) => /^\s*[123]\s*$/.test(textPayload(el)));
    assert.ok(markers.length >= 3, "explicit ordered input keeps visible step numbers");
    const unordered = outlineToDeck(
      parseOutlineMarkdown("# D\n## Not time\n- Collect the supplied source material.\n- Build and inspect the presentation.\n- Record verified results and remaining uncertainty."),
    );
    const unorderedLeaves = validateDeck(unordered, { checkMedia: false }).deck;
    const unorderedMarkers = leafTexts(unorderedLeaves).filter((el) =>
      /^\s*[123]\s*$/.test(textPayload(el)),
    );
    assert.equal(
      unorderedMarkers.length,
      0,
      "unordered bullets must not become a numbered sequence",
    );
  });

  it("keeps narrative prose, empty headings, and literal replacement metacharacters", () => {
    const literal =
      "Keep $&, $$, $`, $', {braces}, <angle brackets>, and \"quoted words\" literal. 中文原文不应被替换或遗漏。";
    const deck = outlineToDeck(
      parseOutlineMarkdown(
        `# Title\n## Context\n${literal}\n## Empty\n## Quotes\n- line one\r\n- still one point`,
      ),
    );
    const parsed = parseOutlineMarkdown(
      `# Title\n## Context\n${literal}\n## Empty\n## Quotes\n- line one\n- still one point`,
    );
    assert.equal(parsed.sections[0].title, "Context");
    assert.deepEqual(parsed.sections[0].bullets, [literal]);
    const { deck: leaves } = validateDeck(deck, { checkMedia: false });
    const joined = leafTexts(leaves).map(textPayload).join("\n");
    assert.ok(joined.includes(literal));
    assert.ok(joined.includes("$&"));
    assert.ok(joined.includes("$$"));
    assert.ok(joined.includes("$`"));
    assert.ok(joined.includes("$'"));
    assert.ok(joined.includes("{braces}"));
    assert.ok(joined.includes("<angle brackets>"));
    assert.ok(joined.includes('"quoted words"'));
    assert.ok(joined.includes("中文原文不应被替换或遗漏。"));
    const emptyPage = leaves.pages.find((page) =>
      (page.elements || []).some(
        (el) => el.type === "text" && textPayload(el) === "Empty",
      ),
    );
    assert.ok(emptyPage, "empty section keeps its real heading");
    const emptyBody = (emptyPage.elements || []).filter(
      (el) =>
        el.type === "text" &&
        textPayload(el).trim() !== "Empty" &&
        textPayload(el).trim() !== "" &&
        !/continued|续|接上|agenda|title/i.test(textPayload(el)),
    );
    assert.equal(emptyBody.length, 0, "empty section must not invent body copy");
    assert.equal(
      leafTexts(leaves).filter((el) => /generated by/i.test(textPayload(el))).length,
      0,
    );
  });

  it("preserves 30 sections and unique ids for legacy outlineToDeck callers", () => {
    const sections = Array.from({ length: 30 }, (_, index) => ({
      title: `区域 ${index + 1} 复盘`,
      bullets: [
        `营收同比 +${index + 1}%`,
        `重点客户 ${(index + 1) * 3} 家`,
        `明年目标:渗透率 ${20 + index + 1}%`,
      ],
    }));
    const deck = outlineToDeck({ title: "全国渠道年度复盘", sections });
    const { deck: leaves } = validateDeck(deck, { checkMedia: false });
    const joined = leafTexts(leaves).map(textPayload).join("\n");
    assert.match(joined, /区域 1 复盘/);
    assert.match(joined, /区域 30 复盘/);
    assert.match(joined, /明年目标:渗透率 50%/);
    const ids = [];
    const pageIds = new Set();
    for (const page of leaves.pages) {
      assert.equal(pageIds.has(page.id), false, `duplicate page id ${page.id}`);
      pageIds.add(page.id);
      for (const el of page.elements || []) {
        assert.equal(ids.includes(el.id), false, `duplicate element id ${el.id}`);
        ids.push(el.id);
      }
    }
    assert.ok(leaves.pages.length >= 32);
    const agenda = leafTexts(leaves).find((el) => /^Agenda/.test(textPayload(el)));
    assert.ok(agenda, "paginated agenda heading is present");
    assert.ok(
      agenda.bounds[3] >= 53,
      `Agenda header height ${agenda.bounds[3]} clips 26pt with insets`,
    );
    const qa = qaDeck(deck, { checkMedia: false, failOn: "med" });
    assert.equal(qa.ok, true, qa.issues.map((issue) => `${issue.pageId}:${issue.code}`).join(","));
  });

  it("falls back from two-column when peers fail measured 18pt capacity", () => {
    const left = "甲".repeat(220);
    const right = "乙".repeat(220);
    assert.ok(left.length <= 240 && right.length <= 240);
    const deck = outlineToDeck(
      parseOutlineMarkdown(`# D\n## Two\n- ${left}\n- ${right}`),
    );
    const { deck: leaves } = validateDeck(deck, { checkMedia: false });
    const joined = leafTexts(leaves).map(textPayload).join("\n");
    assert.equal(joined.split(left).length - 1, 1, "left peer must appear once");
    assert.equal(joined.split(right).length - 1, 1, "right peer must appear once");
    const twoColumnPage = leaves.pages.some((page) => {
      const texts = (page.elements || []).filter((el) => el.type === "text");
      const elL = texts.find((el) => textPayload(el).includes(left));
      const elR = texts.find((el) => textPayload(el).includes(right));
      return (
        elL &&
        elR &&
        elL.id !== elR.id &&
        elL.bounds[1] === elR.bounds[1] &&
        elL.bounds[0] !== elR.bounds[0]
      );
    });
    assert.equal(
      twoColumnPage,
      false,
      "char-count-short CJK peers must not use two-column when they cannot fit",
    );
    const qa = qaDeck(deck, { checkMedia: false, failOn: "med" });
    assert.equal(qa.ok, true, qa.issues.map((issue) => `${issue.pageId}:${issue.code}`).join(","));
  });

  it("keeps explicit source numbers 7, 8, 9 on a sequence page", () => {
    const parsed = parseOutlineMarkdown(
      "# D\n## Explicit sequence\n7. Collect the supplied source material.\n8. Build and inspect the presentation.\n9. Record verified results and remaining uncertainty.",
    );
    assert.equal(parsed.sections[0].listKind, "ordered");
    assert.deepEqual(
      parsed.sections[0].bullets,
      [
        "Collect the supplied source material.",
        "Build and inspect the presentation.",
        "Record verified results and remaining uncertainty.",
      ],
    );
    const deck = outlineToDeck(parsed);
    const { deck: leaves } = validateDeck(deck, { checkMedia: false });
    const texts = leafTexts(leaves).map(textPayload);
    for (const n of ["7", "8", "9"]) {
      assert.ok(
        texts.some((text) => /^\s*$/.test?.("") && new RegExp(`^\\s*${n}\\s*$`).test(text)),
        `source number ${n} must remain visible`,
      );
    }
    assert.equal(
      leafTexts(leaves).filter((el) => /^\s*[123]\s*$/.test(textPayload(el))).length,
      0,
      "source 7,8,9 must not be rewritten as 1,2,3",
    );
  });

  it("does not fabricate outline copy and paginates a long English point", () => {
    const empty = parseOutlineMarkdown("");
    assert.equal(empty.title, "Untitled deck");
    assert.deepEqual(empty.sections, []);
    const emptyDeck = outlineToDeck(empty);
    const emptyJoined = leafTexts(
      validateDeck(emptyDeck, { checkMedia: false }).deck,
    )
      .map(textPayload)
      .join("\n");
    assert.doesNotMatch(emptyJoined, /Add ## headings/);
    assert.equal(
      emptyDeck.pages.filter((page) => page.id !== "cover").length,
      0,
    );

    const segments = Array.from(
      { length: 40 },
      (_, index) =>
        `Checkpoint ${index + 1}: preserve source facts and inspect the exported slide before accepting the result.`,
    );
    const bullet = segments.join(" ");
    const deck = outlineToDeck({
      title: "Long English",
      sections: [{ title: "One long English point", bullets: [bullet] }],
    });
    const { deck: leaves } = validateDeck(deck, { checkMedia: false });
    const joined = leafTexts(leaves).map(textPayload).join("\n");
    for (const segment of segments) {
      assert.ok(joined.includes(segment), segment.slice(0, 24));
      assert.equal(joined.split(segment).length - 1, 1, `duplicate ${segment.slice(0, 16)}`);
    }
    const bodyPages = leaves.pages.filter((page) =>
      (page.elements || []).some(
        (el) => el.type === "text" && /Checkpoint \d+/.test(textPayload(el)),
      ),
    );
    assert.ok(bodyPages.length >= 2, "long English point continues across body pages");
    assert.ok(
      bodyPages.some((page) =>
        (page.elements || []).some(
          (el) => el.type === "text" && /continued|续|接上/i.test(textPayload(el)),
        ),
      ),
    );
    const qa = qaDeck(deck, { checkMedia: false, failOn: "med" });
    assert.equal(qa.ok, true, qa.issues.map((issue) => `${issue.pageId}:${issue.code}`).join(","));
  });

  it("keeps nonconsecutive source numbers, mixed blocks, prose narrative, and title-only decks", () => {
    const numbered = parseOutlineMarkdown(
      "# Sequence\n## Author steps\n7. Alpha\n9. Beta\n42. Gamma",
    );
    assert.equal(numbered.sections[0].listKind, "ordered");
    assert.deepEqual(numbered.sections[0].bullets, ["Alpha", "Beta", "Gamma"]);
    assert.deepEqual(
      numbered.sections[0].blocks.map((block) => block.number),
      ["7", "9", "42"],
    );
    const numberedLeaves = validateDeck(outlineToDeck(numbered), {
      checkMedia: false,
    }).deck;
    const numberedTexts = leafTexts(numberedLeaves).map(textPayload);
    for (const number of ["7", "9", "42"]) {
      assert.ok(
        numberedTexts.some(
          (text) => text.trim() === number || text.startsWith(`${number}.`),
        ),
        `${number} retained`,
      );
    }
    assert.equal(
      numberedTexts.filter((text) => ["1", "2", "3"].includes(text.trim())).length,
      0,
    );

    const mixed = parseOutlineMarkdown(
      "# Mixed\n## Source\nOpening prose.\n7. First ordered fact\n9. Second ordered fact\n- Qualification\nClosing prose.",
    );
    assert.equal(mixed.sections[0].listKind, undefined);
    assert.deepEqual(mixed.sections[0].bullets, [
      "Opening prose.",
      "First ordered fact",
      "Second ordered fact",
      "Qualification",
      "Closing prose.",
    ]);
    const mixedJoined = leafTexts(
      validateDeck(outlineToDeck(mixed), { checkMedia: false }).deck,
    )
      .map(textPayload)
      .join("\n");
    assert.match(mixedJoined, /7[.\s]/);
    assert.match(mixedJoined, /9[.\s]/);
    assert.match(mixedJoined, /First ordered fact/);
    assert.match(mixedJoined, /Qualification/);

    const proseDeck = validateDeck(
      outlineToDeck(
        parseOutlineMarkdown("# Narrative\n## Context\nOpening prose.\nFollowing prose."),
      ),
      { checkMedia: false },
    ).deck;
    const proseTexts = leafTexts(proseDeck);
    const opening = proseTexts.find((el) => textPayload(el).includes("Opening prose."));
    const following = proseTexts.find((el) =>
      textPayload(el).includes("Following prose."),
    );
    assert.ok(opening && following);
    assert.ok(
      opening.id === following.id ||
        (opening.bounds[0] === following.bounds[0] &&
          opening.bounds[1] < following.bounds[1]),
      "two prose lines must stay narrative, not columns",
    );

    const titleOnly = parseOutlineMarkdown("# Actual title");
    assert.equal(titleOnly.title, "Actual title");
    assert.deepEqual(titleOnly.sections, []);
    const titleJoined = leafTexts(
      validateDeck(outlineToDeck(titleOnly), { checkMedia: false }).deck,
    )
      .map(textPayload)
      .join("\n");
    assert.doesNotMatch(titleJoined, /Add ## headings|Add.*bullets|generated by/i);
    assert.match(titleJoined, /Actual title/);
  });

  it("preview wraps long tokens without changing source characters", () => {
    const token = "abcdefghijklmnopqrstuvwxyz".repeat(30);
    const deck = outlineToDeck({
      title: "Literal token",
      sections: [{ title: "Source bytes", bullets: [token] }],
    });
    const html = renderPreviewHtml(deck, root);
    assert.match(html, /\.text-inner \{[^}]*overflow-wrap:anywhere/);
    assert.match(html, /\.text \{[^}]*overflow-wrap:anywhere/);
    const bodies = validateDeck(deck, { checkMedia: false })
      .deck.pages.flatMap((page) => page.elements || [])
      .filter((el) => el.type === "text" && String(el.id).endsWith("-body"))
      .map(textPayload);
    assert.equal(bodies.join(""), token);
    for (const chunk of bodies) {
      assert.ok(html.includes(chunk), "preview must keep authored chunk bytes");
    }
    assert.doesNotMatch(html, /abcde fghij/);
  });

  it("concatenates split chunks exactly and sizes continuation kicker for 18pt", () => {
    const prose = "A single fact with punctuation. ".repeat(100);
    const token = "abcdefghijklmnopqrstuvwxyz".repeat(30);
    assert.equal(splitTextToFit(prose, 20, 864, 340).join(""), prose);
    assert.equal(splitTextToFit(token, 20, 864, 340).join(""), token);
    const deck = outlineToDeck({
      title: "Long",
      sections: [{ title: "Narrative", bullets: [prose] }],
    });
    const { deck: leaves } = validateDeck(deck, { checkMedia: false });
    const bodies = leaves.pages
      .flatMap((page) => page.elements || [])
      .filter((el) => el.type === "text" && String(el.id).endsWith("-body"))
      .map(textPayload)
      .join("");
    assert.equal(bodies, prose);
    const kicker = leafTexts(leaves).find((el) => /continued/i.test(textPayload(el)));
    assert.ok(kicker, "continuation kicker is present");
    assert.ok(
      kicker.bounds[3] >= ptToPx(18) * 1.25 + 2 * TEXT_INSET_Y_PX,
      `kicker height ${kicker.bounds[3]} cannot fit 18pt with insets`,
    );
  });

  it("measures section titles or throws a contextual title limit", () => {
    const wrapped = "Section heading that must wrap onto additional lines for capacity";
    const deck = outlineToDeck({
      title: "D",
      sections: [{ title: wrapped, bullets: ["Body"] }],
    });
    const { deck: leaves } = validateDeck(deck, { checkMedia: false });
    const heading = leafTexts(leaves).find((el) => textPayload(el) === wrapped);
    assert.ok(heading);
    assert.ok(heading.bounds[3] >= 56);
    assert.throws(
      () =>
        outlineToDeck({
          title: "D",
          sections: [{ title: "字".repeat(2000), bullets: ["Body"] }],
        }),
      (err) =>
        err instanceof OpenPptError &&
        err.code === ErrorCodes.RESOURCE_LIMIT &&
        /title/i.test(`${err.message} ${err.details?.context || ""}`),
    );
  });

  it("fits sequence under tall CJK titles and keeps lexical source numbers", () => {
    for (const chars of [50, 100, 250]) {
      const heading = "章".repeat(chars);
      const deck = outlineToDeck(
        parseOutlineMarkdown(`# Titles\n## ${heading}\n7. Alpha\n8. Beta\n9. Gamma`),
      );
      validateDeck(deck, { checkMedia: false });
      const qa = qaDeck(deck, { checkMedia: false, failOn: "med" });
      assert.equal(
        qa.ok,
        true,
        `${chars}: ${qa.issues.map((issue) => `${issue.pageId}:${issue.code}`).join(",")}`,
      );
    }
    const single = parseOutlineMarkdown("# Numbers\n## One\n7. Single original step");
    assert.deepEqual(single.sections[0].bullets, ["Single original step"]);
    const singleText = leafTexts(
      validateDeck(outlineToDeck(single), { checkMedia: false }).deck,
    )
      .map(textPayload)
      .join("\n");
    assert.match(singleText, /7/);
    const large = parseOutlineMarkdown(
      "# Numbers\n## Large\n9007199254740993. Alpha\n9007199254740995. Beta",
    );
    assert.equal(large.sections[0].blocks[0].number, "9007199254740993");
    const largeText = leafTexts(
      validateDeck(outlineToDeck(large), { checkMedia: false }).deck,
    )
      .map(textPayload)
      .join("\n");
    assert.ok(largeText.includes("9007199254740993"));
    assert.ok(largeText.includes("9007199254740995"));
    assert.equal(largeText.includes("9007199254740992"), false);
  });

  it("falls back when a later sequence chunk cannot fit its step box", () => {
    const phrase = "The final step keeps every supplied detail. ";
    const long = phrase.repeat(50);
    const deck = outlineToDeck(
      parseOutlineMarkdown(
        `# Steps\n## Ordered details\n1. Alpha\n2. Beta\n3. Gamma\n4. ${long}`,
      ),
    );
    const { deck: leaves } = validateDeck(deck, { checkMedia: false });
    const bodies = leaves.pages
      .flatMap((page) => page.elements || [])
      .filter((el) => el.type === "text" && String(el.id).endsWith("-body"))
      .map(textPayload);
    const body = bodies.join("");
    const expected = `1. Alpha\n2. Beta\n3. Gamma\n4. ${long}`;
    const norm = (value) => value.replace(/\s/g, "");
    assert.equal(body.split(phrase.trim()).length - 1, 50);
    assert.equal(norm(body), norm(expected));
    const qa = qaDeck(deck, { checkMedia: false, failOn: "med" });
    assert.equal(
      qa.ok,
      true,
      qa.issues.map((issue) => `${issue.pageId}:${issue.code}`).join(","),
    );
  });

  it("rejects a huge card/sequence section before materializing pages", () => {
    assert.throws(
      () =>
        sectionPages("bounded", {
          title: "Bounded input",
          bullets: Array.from({ length: 1000 }, (_, index) => `Point ${index}`),
        }),
      (err) => err instanceof OpenPptError && err.code === ErrorCodes.RESOURCE_LIMIT,
    );
  });

  it("materializes shipped C3 page fragments into valid decks", () => {
    const vars = {
      TITLE: "Title",
      BODY: "Body copy",
      KICKER: "",
      BODY_A: "Left peer",
      BODY_B: "Right peer",
      BODY_1: "Card one",
      BODY_2: "Card two",
      BODY_3: "Card three",
      VALUE_1: "42",
      LABEL_1: "Accepted checks",
      VALUE_2: "180 ms",
      LABEL_2: "Median latency",
      VALUE_3: "92%",
      LABEL_3: "Coverage",
      STEP_1_N: "1",
      STEP_1_T: "Collect",
      STEP_2_N: "2",
      STEP_2_T: "Build",
      STEP_3_N: "3",
      STEP_3_T: "Record",
    };
    for (const name of PAGE_PROTOTYPE_NAMES) {
      const page = fillPrototype(loadPagePrototype(name), vars);
      page.id = `frag-${name}`;
      const deck = {
        version: "openppt-1",
        size: [960, 540],
        theme: {
          colors: {
            primary: "#2563EB",
            accent: "#F59E0B",
            text: "#111827",
            muted: "#6B7280",
            background: "#FFFFFF",
            surface: "#F8FAFC",
          },
          textStyles: outlineTextStyles(),
        },
        pages: [page],
      };
      validateDeck(JSON.parse(JSON.stringify(deck)), { checkMedia: false });
      const qa = qaDeck(deck, { checkMedia: false, failOn: "med" });
      assert.equal(qa.ok, true, `${name}: ${qa.issues.map((issue) => issue.code).join(",")}`);
    }
  });

  it("rejects overflow in outlineToDeck and unreadable titles before partial work", () => {
    assert.throws(
      () =>
        outlineToDeck({
          title: "Huge",
          sections: Array.from({ length: 260 }, (_, index) => ({
            title: `S${index + 1}`,
            bullets: ["point"],
          })),
        }),
      (err) => err instanceof OpenPptError && err.code === ErrorCodes.RESOURCE_LIMIT,
    );
    assert.throws(
      () =>
        outlineToDeck({
          title: "字".repeat(2000),
          sections: [],
        }),
      (err) =>
        err instanceof OpenPptError &&
        err.code === ErrorCodes.RESOURCE_LIMIT &&
        /title/i.test(`${err.message} ${err.details?.context || ""}`),
    );
  });

  it("rejects invalid size and resource overflow before writing a project", () => {
    assert.throws(
      () =>
        outlineToDeck(
          { title: "Small", sections: [{ title: "One", bullets: ["Body"] }] },
          { size: [320, 180] },
        ),
      (err) => err instanceof OpenPptError && err.code === ErrorCodes.LAYOUT,
    );
    const work = mkdtempSync(join(tmpdir(), "openppt-c3-limit-"));
    try {
      const mdPath = join(work, "outline.md");
      const dest = join(work, "out");
      const sections = Array.from(
        { length: 260 },
        (_, index) => `## S${index + 1}\n- point ${index + 1}\n`,
      ).join("");
      writeFileSync(mdPath, `# Huge\n${sections}`, "utf8");
      assert.throws(
        () => projectFromOutline(mdPath, dest),
        (err) => err instanceof OpenPptError && err.code === ErrorCodes.RESOURCE_LIMIT,
      );
      assert.equal(existsSync(dest), false, "failed from-outline must not leave a partial project");
    } finally {
      rmSync(work, { recursive: true, force: true });
    }
  });
});
