/**
 * Build an OpenPPT deck from a simple markdown outline.
 *
 * Supported:
 *   # Deck title
 *   ## Page title
 *   - bullet
 *   - bullet
 *   plain paragraph lines under a page
 */

import {
  mkdirSync,
  writeFileSync,
  existsSync,
  readFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { OpenPptError, ErrorCodes } from "./errors.js";
import { writeDeckFileAtomic } from "./project-write.js";
import { validateDeck } from "./validate.js";

const rootDir = join(dirname(fileURLToPath(import.meta.url)), "..");
const THEME_IDS = new Set(["default", "dark", "magazine", "report"]);

/**
 * @param {string} themeId
 */
function loadThemeColors(themeId) {
  if (!THEME_IDS.has(themeId)) {
    throw new OpenPptError(
      ErrorCodes.IO,
      `Unknown theme "${themeId}" (available: default, dark, magazine, report)`,
      { themeId },
    );
  }
  const path = join(rootDir, "themes", `${themeId}.json`);
  if (!existsSync(path)) {
    throw new OpenPptError(
      ErrorCodes.IO,
      `Unknown theme "${themeId}"`,
      { themeId },
    );
  }
  return JSON.parse(readFileSync(path, "utf8")).colors || {};
}

/**
 * Parse outline markdown into { title, sections: [{ title, bullets: string[] }] }.
 * @param {string} md
 */
export function parseOutlineMarkdown(md) {
  const lines = String(md).split(/\r?\n/);
  let title = "Untitled deck";
  /** @type {{ title: string, bullets: string[] }[]} */
  const sections = [];
  /** @type {{ title: string, bullets: string[] } | null} */
  let current = null;

  for (const raw of lines) {
    const line = raw.trimEnd();
    const t = line.trim();
    if (!t) continue;

    if (/^#\s+/.test(t) && !/^##/.test(t)) {
      title = t.replace(/^#\s+/, "").trim() || title;
      continue;
    }
    if (/^##\s+/.test(t)) {
      current = { title: t.replace(/^##\s+/, "").trim() || "Section", bullets: [] };
      sections.push(current);
      continue;
    }
    if (!current) {
      // create implicit first section from body
      current = { title: "Overview", bullets: [] };
      sections.push(current);
    }
    if (/^[-*+]\s+/.test(t)) {
      current.bullets.push(t.replace(/^[-*+]\s+/, "").trim());
    } else if (/^\d+\.\s+/.test(t)) {
      current.bullets.push(t.replace(/^\d+\.\s+/, "").trim());
    } else {
      current.bullets.push(t);
    }
  }

  if (sections.length === 0) {
    sections.push({ title: "Overview", bullets: ["Add ## headings and - bullets"] });
  }
  return { title, sections };
}

/**
 * Build deck IR object from outline.
 * @param {{ title: string, sections: { title: string, bullets: string[] }[] }} outline
 * @param {{ theme?: string, size?: [number, number] }} [options]
 */
export function outlineToDeck(outline, options = {}) {
  const theme = options.theme || "default";
  const colors = loadThemeColors(theme);
  if (
    options.size !== undefined &&
    (!Array.isArray(options.size) ||
      options.size.length !== 2 ||
      options.size[0] !== 960 ||
      options.size[1] !== 540)
  ) {
    throw new OpenPptError(
      ErrorCodes.LAYOUT,
      "from-outline currently supports only the 960x540 canvas",
      { size: options.size },
    );
  }
  const size = [960, 540];

  /** @type {object[]} */
  const pages = [
    {
      id: "cover",
      background: { type: "solid", color: "$background" },
      elements: [
        {
          id: "cover-stack",
          type: "group",
          layout: "stack",
          bounds: [60, 160, 840, 240],
          gap: 20,
          children: [
            {
              id: "cover-title",
              type: "text",
              height: 80,
              text: outline.title,
              fontSize: 34,
              bold: true,
              color: "$primary",
            },
            {
              id: "cover-sub",
              type: "text",
              height: 40,
              text: `${outline.sections.length} sections · generated by OpenPPT`,
              fontSize: 16,
              color: "$muted",
            },
          ],
        },
      ],
    },
  ];

  // TOC when enough sections. Seven 36px entries plus six 16px gaps fit 380px.
  if (outline.sections.length >= 2) {
    const tocChunks = [];
    for (let start = 0; start < outline.sections.length; start += 7) {
      tocChunks.push(outline.sections.slice(start, start + 7));
    }
    for (let chunkIndex = 0; chunkIndex < tocChunks.length; chunkIndex += 1) {
      const suffix = chunkIndex === 0 ? "" : `-${chunkIndex + 1}`;
      pages.push({
        id: `toc${suffix}`,
        background: { type: "solid", color: "$surface" },
        elements: [
          {
            id: `toc-h${suffix}`,
            type: "text",
            bounds: [48, 32, 864, 40],
            text:
              tocChunks.length === 1
                ? "Agenda"
                : `Agenda ${chunkIndex + 1}/${tocChunks.length}`,
            fontSize: 26,
            bold: true,
            color: "$primary",
          },
          {
            id: `toc-list${suffix}`,
            type: "group",
            layout: "stack",
            bounds: [64, 100, 832, 380],
            gap: 16,
            children: tocChunks[chunkIndex].map((sec, localIndex) => {
              const sectionIndex = chunkIndex * 7 + localIndex;
              return {
                id: `toc-${sectionIndex + 1}`,
                type: "text",
                height: 36,
                text: `${String(sectionIndex + 1).padStart(2, "0")}  ${sec.title}`,
                fontSize: 18,
                color: "$text",
              };
            }),
          },
        ],
      });
    }
  }

  for (let i = 0; i < outline.sections.length; i += 1) {
    const sec = outline.sections[i];
    const body =
      sec.bullets.length > 0
        ? sec.bullets.map((b) => `• ${b}`).join("\n")
        : " ";
    pages.push({
      id: `sec-${i + 1}`,
      background: { type: "solid", color: "$background" },
      elements: [
        {
          id: `sec-${i + 1}-panel`,
          type: "group",
          layout: "stack",
          bounds: [48, 36, 864, 468],
          gap: 20,
          children: [
            {
              id: `sec-${i + 1}-h`,
              type: "text",
              height: 48,
              text: sec.title,
              fontSize: 26,
              bold: true,
              color: "$primary",
            },
            {
              id: `sec-${i + 1}-b`,
              type: "text",
              flex: 1,
              text: body,
              fontSize: 16,
              color: "$text",
            },
          ],
        },
      ],
    });
  }

  return {
    version: "openppt-1",
    title: outline.title,
    size,
    theme: { colors },
    pages,
  };
}

/**
 * Read markdown file → write OpenPPT project.
 * @param {string} mdPath
 * @param {string} outDir
 * @param {{ force?: boolean, theme?: string }} [options]
 */
export function projectFromOutline(mdPath, outDir, options = {}) {
  const { force = false, theme = "default" } = options;
  const abs = resolve(mdPath);
  if (!existsSync(abs)) {
    throw new OpenPptError(ErrorCodes.IO, `Outline not found: ${abs}`);
  }
  const dest = resolve(outDir);
  const deckPath = join(dest, "deck.json");
  if (existsSync(deckPath) && !force) {
    throw new OpenPptError(
      ErrorCodes.EXPORT,
      `deck.json already exists in ${dest} (pass --force)`,
    );
  }
  const md = readFileSync(abs, "utf8");
  const outline = parseOutlineMarkdown(md);
  const deck = outlineToDeck(outline, { theme });
  validateDeck(JSON.parse(JSON.stringify(deck)), { checkMedia: false });
  mkdirSync(join(dest, "media"), { recursive: true });
  const keep = join(dest, "media", ".gitkeep");
  if (!existsSync(keep)) writeFileSync(keep, "", "utf8");
  writeDeckFileAtomic(deckPath, `${JSON.stringify(deck, null, 2)}\n`, { force });
  return { deckPath, pageCount: deck.pages.length, title: deck.title };
}
